name: Michael Houser Photography
favicon: null
layout_spectrum: 0.8812459367327392
typography_spectrum: 0.8722875076346099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf8ef'
    - '#13140e'
    - '#cbab85'
    - '#978463'
    - '#3f384d'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
