analytics: {}
color:
  brandColors:
    - '#fcf8ef'
    - '#13140e'
    - '#cbab85'
    - '#978463'
    - '#3f384d'
  brandStrength: 0
  lightness: 0.514358
  rhythmicContrast: 0.5
  saturation: 0
cta: {}
layout_spectrum: 0.8812459367327392
name: Michael Houser Photography
opengraph: {}
purpose: []
typography_spectrum: 1
